Update Postgres.yml

diff --git a/.github/workflows/Postgres.yml b/.github/workflows/Postgres.yml
--- a/.github/workflows/Postgres.yml
+++ b/.github/workflows/Postgres.yml
@@ -95,7 +95,7 @@ jobs:
       #   env:
       #     TYPE: server
       - name: Run Tests
-        run: cd ~/frappe-bench/ && bench --site test_site run-tests --app frappe --doctype "Role" --coverage || echo "Tests completed with errors, but proceeding..."
+        run: cd ~/frappe-bench/ && bench --site test_site run-tests --app erpnext --doctype "Opportunity" --coverage || echo "Tests completed with errors, but proceeding..."
         env:
           TYPE: server
           
