Update postgres-test.yml

diff --git a/.github/workflows/postgres-test.yml b/.github/workflows/postgres-test.yml
--- a/.github/workflows/postgres-test.yml
+++ b/.github/workflows/postgres-test.yml
@@ -87,17 +87,17 @@ jobs:
           bench --site test_site install-app erpnext
         env:
           CI: 'Yes'
-      # - name: Run Tests
-      #   working-directory: /home/runner/frappe-bench
-      #   run: |
-      #     bench --site test_site set-config allow_tests true
-      #     bench --site test_site run-tests 
-      #   env:
-          TYPE: server
       - name: Run Tests
-        run: cd ~/frappe-bench/ && bench --site test_site run-tests --app erpnext  --coverage  || echo "Tests completed with errors, but proceeding..."
+        working-directory: /home/runner/frappe-bench
+        run: |
+          bench --site test_site set-config allow_tests true
+          bench --site test_site run-tests 
         env:
           TYPE: server
+      # - name: Run Tests
+      #   run: cd ~/frappe-bench/ && bench --site test_site run-tests --app erpnext  --coverage  || echo "Tests completed with errors, but proceeding..."
+      #   env:
+      #     TYPE: server
 
       # - name: Run Tests
       #   run: |
